name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./message/pom.xml
          mvn clean package -f ./app push/pom.xml
          mvn clean package -f ./sms/pom.xml

      - name: Docker Build and push for Message
        uses: docker/build-push-action@v4
        with:
          context: ./message
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/message:latest
            ghcr.io/${{ github.repository }}/message:${{ github.ref_name }}
            
      - name: Docker Build and push for AppPush
        uses: docker/build-push-action@v4
        with:
          context: ./app push
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/app-push:latest
            ghcr.io/${{ github.repository }}/app-push:${{ github.ref_name }}
            
      - name: Docker Build and push for Sms
        uses: docker/build-push-action@v4
        with:
          context: ./sms
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sms:latest
            ghcr.io/${{ github.repository }}/sms:${{ github.ref_name }}
            
